#! /bin/sh

VERSION='v0.1.1'

usage() {
    cat <<EOF
Usage: ssl-reverse-proxy
       ssl-reverse-proxy -h | --help
       ssl-reverse-proxy --version

Options:
    -h, --help  Show this screen.
    --version   Show version.
EOF
}

if [ "x$1" = 'x-h' ] || [ "x$1" = 'x--help' ]; then
    usage
elif [ "x$1" = 'x--version' ]; then
    echo "ssl-reverse-proxy $VERSION"
else
    ( test -x nginx || ( \
	INSTALL="$(realpath "$(dirname "$0")")" && \
	DIR="$(mktemp -d)" && \
	cd "$DIR" && \
	wget 'http://ftp.us.debian.org/debian/pool/main/n/nginx/nginx-light_1.18.0-6.1+deb11u3_amd64.deb' -O nginx.deb && \
	sha256sum nginx.deb | grep -Fw 'e39eaad5a7779c5971ed923a6413da94a5094b97481bfedb96d7330a9d56b123' && \
	dpkg-deb -x nginx.deb root && \
	mv root/usr/sbin/nginx "$INSTALL" \
    ) ) && \
	openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/nginx-ssl.key -out /tmp/nginx-ssl.crt -subj "/C=IO/ST=Home/L=Localhost/O=User/CN=localhost" &&
	./nginx -c "$(realpath nginx.conf)"
fi
